server:
  port: 3001

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848,localhost:8948,localhost:9048
        namespace: 9874d759-858b-4564-a5af-81fb8bc02975
